CONFIG_BSP_USING_ADC1=y
CONFIG_BSP_USING_PWMT2=y
CONFIG_BSP_USING_SDIO=y
CONFIG_BSP_USING_SDMMC2=y
# CONFIG_BSP_USING_TOUCHD is not set
CONFIG_RT_MAIN_THREAD_STACK_SIZE=4096
CONFIG_RT_MAIN_THREAD_PRIORITY=15
CONFIG_RT_USING_DFS_ELMFAT=y
CONFIG_RT_USING_ULOG=y
CONFIG_ULOG_OUTPUT_FLOAT=y
CONFIG_ULOG_OUTPUT_THREAD_NAME=y
CONFIG_USING_ACPU_CTRL_FWK=y
CONFIG_USING_BUTTON_LIB=y
CONFIG_BUTTON_ADV_ACTION_CHECK_DELAY=1000
CONFIG_ADC_BUTTON_GROUP1_BUTTON1_VOLT=2970
CONFIG_ADC_BUTTON_GROUP1_BUTTON1_RANGE=100
CONFIG_ADC_BUTTON_GROUP1_BUTTON2_VOLT=2580
CONFIG_ADC_BUTTON_GROUP1_BUTTON2_RANGE=100
CONFIG_ADC_BUTTON_GROUP1_BUTTON3_VOLT=2190
CONFIG_ADC_BUTTON_GROUP1_BUTTON3_RANGE=100
CONFIG_USING_CPU_USAGE_PROFILER=y
CONFIG_CAMERA_READ_TIMEOUT_MS=2000
CONFIG_CAMERA_SCCB_SCL_PIN=27
CONFIG_CAMERA_SCCB_SDA_PIN=20
CONFIG_CAMERA_XCLK_PIN=39
