from building import *
import os

cwd = GetCurrentDir()

src = Glob(os.path.join(cwd, 'src', '*.c'))
inc = [cwd, os.path.join(cwd, 'include')]

group = DefineGroup('BF30A2',
                    src,
                    depend = ['PKG_USING_BF30A2'],
                    CPPPATH = inc)

Return('group')
